// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: AGBikeDashboard

#ifndef _AGBIKEDASHBOARD_UI_H
#define _AGBIKEDASHBOARD_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_MainPanel;
extern lv_obj_t * ui_SportsmodePanel;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_SportsSlider;
extern lv_obj_t * ui_SportsmodehedingLabel;
extern lv_obj_t * ui_TempPanel;
extern lv_obj_t * ui_TempunitLabel;
extern lv_obj_t * ui_TempLabel;
extern lv_obj_t * ui_TempSlider;
extern lv_obj_t * ui_TemphedingLabel;
extern lv_obj_t * ui_AttributePanel;
extern lv_obj_t * ui_voltagePanel;
extern lv_obj_t * ui_VoltageLabel;
extern lv_obj_t * ui_voltageheadingLabel;
extern lv_obj_t * ui_voltageunitLabel;
extern lv_obj_t * ui_currentPanel;
extern lv_obj_t * ui_CurrentLabel;
extern lv_obj_t * ui_currentheadingLabel;
extern lv_obj_t * ui_currentunitLabel;
extern lv_obj_t * ui_powerPanel;
extern lv_obj_t * ui_PowerLabel;
extern lv_obj_t * ui_powerunitLabel;
extern lv_obj_t * ui_PowerheadingLabel;
extern lv_obj_t * ui_AmpHourPanel;
extern lv_obj_t * ui_AmpHourLabel;
extern lv_obj_t * ui_powerunitLabel2;
extern lv_obj_t * ui_AmpHourheadingLabel;
extern lv_obj_t * ui_SocPanel;
extern lv_obj_t * ui_SocLabel;
extern lv_obj_t * ui_socunitLabel3;
extern lv_obj_t * ui_socheadingLabel3;
extern lv_obj_t * ui_WattHourPanel;
extern lv_obj_t * ui_WattHourLabel;
extern lv_obj_t * ui_watthourunitLabel;
extern lv_obj_t * ui_WattHourheadingLabel;
extern lv_obj_t * ui_EcoModePanel;
extern lv_obj_t * ui_EcoModeLabel;
extern lv_obj_t * ui_EcoModeunitLabel;
extern lv_obj_t * ui_EcoModeheadingLabel;
extern lv_obj_t * ui_SportsModePanel;
extern lv_obj_t * ui_SportsModeLabel;
extern lv_obj_t * ui_SportsModeunitLabel;
extern lv_obj_t * ui_SportsModeheadingLabel;
extern lv_obj_t * ui____initial_actions0;





LV_FONT_DECLARE(ui_font_AGFont14);
LV_FONT_DECLARE(ui_font_Font12);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
