// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: AGBikeDashboard

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Screen1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Screen1, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Screen1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_MainPanel, 320);
    lv_obj_set_height(ui_MainPanel, 240);
    lv_obj_set_align(ui_MainPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MainPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MainPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SportsmodePanel = lv_obj_create(ui_MainPanel);
    lv_obj_set_width(ui_SportsmodePanel, 66);
    lv_obj_set_height(ui_SportsmodePanel, 30);
    lv_obj_set_x(ui_SportsmodePanel, 115);
    lv_obj_set_y(ui_SportsmodePanel, -92);
    lv_obj_set_align(ui_SportsmodePanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SportsmodePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SportsmodePanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SportsmodePanel, lv_color_hex(0x3C3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SportsmodePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SportsmodePanel, lv_color_hex(0x313131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SportsmodePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SportsmodePanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_SportsmodePanel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SportsmodePanel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SportsmodePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SportsmodePanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SportsmodePanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_SportsmodePanel, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_SportsmodePanel, -1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_btn_create(ui_SportsmodePanel);
    lv_obj_set_width(ui_Button2, 66);
    lv_obj_set_height(ui_Button2, 30);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SportsSlider = lv_slider_create(ui_MainPanel);
    lv_slider_set_value(ui_SportsSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SportsSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SportsSlider, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_SportsSlider, 215);
    lv_obj_set_height(ui_SportsSlider, 15);
    lv_obj_set_x(ui_SportsSlider, -35);
    lv_obj_set_y(ui_SportsSlider, -82);
    lv_obj_set_align(ui_SportsSlider, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_SportsSlider, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SportsSlider, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SportsSlider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SportsSlider, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SportsSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SportsSlider, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SportsSlider, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SportsSlider, lv_color_hex(0x00FFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SportsSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SportsSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SportsSlider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SportsSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_SportsmodehedingLabel = lv_label_create(ui_MainPanel);
    lv_obj_set_width(ui_SportsmodehedingLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SportsmodehedingLabel, LV_SIZE_CONTENT);    /// 175
    lv_obj_set_x(ui_SportsmodehedingLabel, -41);
    lv_obj_set_y(ui_SportsmodehedingLabel, -96);
    lv_obj_set_align(ui_SportsmodehedingLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SportsmodehedingLabel, "Sport's Mode");
    lv_obj_set_style_text_color(ui_SportsmodehedingLabel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SportsmodehedingLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SportsmodehedingLabel, &ui_font_AGFont14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempPanel = lv_obj_create(ui_MainPanel);
    lv_obj_set_width(ui_TempPanel, 66);
    lv_obj_set_height(ui_TempPanel, 30);
    lv_obj_set_x(ui_TempPanel, 115);
    lv_obj_set_y(ui_TempPanel, 96);
    lv_obj_set_align(ui_TempPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TempPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TempPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TempPanel, lv_color_hex(0x3C3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TempPanel, lv_color_hex(0x313131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TempPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TempPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_TempPanel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_TempPanel, lv_color_hex(0xFFFF10), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_TempPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_TempPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_TempPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_TempPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_TempPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempunitLabel = lv_label_create(ui_TempPanel);
    lv_obj_set_width(ui_TempunitLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempunitLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempunitLabel, 21);
    lv_obj_set_y(ui_TempunitLabel, 8);
    lv_obj_set_align(ui_TempunitLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempunitLabel, "*C");
    lv_obj_set_style_text_color(ui_TempunitLabel, lv_color_hex(0xFFFF10), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TempunitLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempunitLabel, &ui_font_Font12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempLabel = lv_label_create(ui_TempPanel);
    lv_obj_set_width(ui_TempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempLabel, 1);
    lv_obj_set_y(ui_TempLabel, -3);
    lv_obj_set_align(ui_TempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempLabel, "00");
    lv_obj_set_style_text_color(ui_TempLabel, lv_color_hex(0xFFFF10), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TempLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempLabel, &ui_font_Font12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempSlider = lv_slider_create(ui_MainPanel);
    lv_slider_set_range(ui_TempSlider, 0, 120);
    lv_slider_set_value(ui_TempSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_TempSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_TempSlider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_TempSlider, 215);
    lv_obj_set_height(ui_TempSlider, 15);
    lv_obj_set_x(ui_TempSlider, -34);
    lv_obj_set_y(ui_TempSlider, 105);
    lv_obj_set_align(ui_TempSlider, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_TempSlider, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TempSlider, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempSlider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TempSlider, lv_color_hex(0xFFFF10), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TempSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TempSlider, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TempSlider, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TempSlider, lv_color_hex(0xFFFF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TempSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TempSlider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TemphedingLabel = lv_label_create(ui_MainPanel);
    lv_obj_set_width(ui_TemphedingLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TemphedingLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TemphedingLabel, -37);
    lv_obj_set_y(ui_TemphedingLabel, 92);
    lv_obj_set_align(ui_TemphedingLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TemphedingLabel, "Temperature");
    lv_obj_set_style_text_color(ui_TemphedingLabel, lv_color_hex(0xFFFF10), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TemphedingLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TemphedingLabel, &ui_font_AGFont14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AttributePanel = lv_obj_create(ui_MainPanel);
    lv_obj_set_width(ui_AttributePanel, 307);
    lv_obj_set_height(ui_AttributePanel, 144);
    lv_obj_set_x(ui_AttributePanel, -2);
    lv_obj_set_y(ui_AttributePanel, 0);
    lv_obj_set_align(ui_AttributePanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AttributePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_AttributePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AttributePanel, lv_color_hex(0x313131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AttributePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AttributePanel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AttributePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_AttributePanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_AttributePanel, lv_color_hex(0xFFFF10), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AttributePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_AttributePanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_AttributePanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_AttributePanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_AttributePanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_voltagePanel = lv_obj_create(ui_AttributePanel);
    lv_obj_set_width(ui_voltagePanel, 70);
    lv_obj_set_height(ui_voltagePanel, 65);
    lv_obj_set_x(ui_voltagePanel, -112);
    lv_obj_set_y(ui_voltagePanel, -33);
    lv_obj_set_align(ui_voltagePanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_voltagePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_voltagePanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_voltagePanel, lv_color_hex(0x3C3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_voltagePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_voltagePanel, lv_color_hex(0x313131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_voltagePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_voltagePanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_voltagePanel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_voltagePanel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_voltagePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_voltagePanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_voltagePanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_voltagePanel, -2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_voltagePanel, -1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VoltageLabel = lv_label_create(ui_voltagePanel);
    lv_obj_set_width(ui_VoltageLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VoltageLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_VoltageLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VoltageLabel, "00");
    lv_obj_set_style_text_color(ui_VoltageLabel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VoltageLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VoltageLabel, &ui_font_Font12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_voltageheadingLabel = lv_label_create(ui_voltagePanel);
    lv_obj_set_width(ui_voltageheadingLabel, 48);
    lv_obj_set_height(ui_voltageheadingLabel, 8);
    lv_obj_set_x(ui_voltageheadingLabel, -1);
    lv_obj_set_y(ui_voltageheadingLabel, -24);
    lv_obj_set_align(ui_voltageheadingLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_voltageheadingLabel, "VOLTAGE");
    lv_obj_set_style_text_color(ui_voltageheadingLabel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_voltageheadingLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_voltageheadingLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_voltageunitLabel = lv_label_create(ui_voltagePanel);
    lv_obj_set_width(ui_voltageunitLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_voltageunitLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_voltageunitLabel, 19);
    lv_obj_set_y(ui_voltageunitLabel, 21);
    lv_obj_set_align(ui_voltageunitLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_voltageunitLabel, "V");
    lv_obj_set_style_text_color(ui_voltageunitLabel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_voltageunitLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_voltageunitLabel, &ui_font_AGFont14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_currentPanel = lv_obj_create(ui_AttributePanel);
    lv_obj_set_width(ui_currentPanel, 70);
    lv_obj_set_height(ui_currentPanel, 65);
    lv_obj_set_x(ui_currentPanel, -36);
    lv_obj_set_y(ui_currentPanel, -33);
    lv_obj_set_align(ui_currentPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_currentPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_currentPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_currentPanel, lv_color_hex(0x3C3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_currentPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_currentPanel, lv_color_hex(0x313131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_currentPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_currentPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_currentPanel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_currentPanel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_currentPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_currentPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_currentPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_currentPanel, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_currentPanel, -1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CurrentLabel = lv_label_create(ui_currentPanel);
    lv_obj_set_width(ui_CurrentLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CurrentLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CurrentLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CurrentLabel, "00");
    lv_obj_set_style_text_color(ui_CurrentLabel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CurrentLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CurrentLabel, &ui_font_Font12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_currentheadingLabel = lv_label_create(ui_currentPanel);
    lv_obj_set_width(ui_currentheadingLabel, 54);
    lv_obj_set_height(ui_currentheadingLabel, 8);
    lv_obj_set_x(ui_currentheadingLabel, 3);
    lv_obj_set_y(ui_currentheadingLabel, -25);
    lv_obj_set_align(ui_currentheadingLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_currentheadingLabel, "CURRENT");
    lv_obj_set_style_text_color(ui_currentheadingLabel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_currentheadingLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_currentheadingLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_currentunitLabel = lv_label_create(ui_currentPanel);
    lv_obj_set_width(ui_currentunitLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_currentunitLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_currentunitLabel, 19);
    lv_obj_set_y(ui_currentunitLabel, 21);
    lv_obj_set_align(ui_currentunitLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_currentunitLabel, "A");
    lv_obj_set_style_text_color(ui_currentunitLabel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_currentunitLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_currentunitLabel, &ui_font_AGFont14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_powerPanel = lv_obj_create(ui_AttributePanel);
    lv_obj_set_width(ui_powerPanel, 70);
    lv_obj_set_height(ui_powerPanel, 65);
    lv_obj_set_x(ui_powerPanel, 40);
    lv_obj_set_y(ui_powerPanel, -33);
    lv_obj_set_align(ui_powerPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_powerPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_powerPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_powerPanel, lv_color_hex(0x3C3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_powerPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_powerPanel, lv_color_hex(0x313131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_powerPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_powerPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_powerPanel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_powerPanel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_powerPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_powerPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_powerPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_powerPanel, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_powerPanel, -1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PowerLabel = lv_label_create(ui_powerPanel);
    lv_obj_set_width(ui_PowerLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PowerLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PowerLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PowerLabel, "00");
    lv_obj_set_style_text_color(ui_PowerLabel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PowerLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PowerLabel, &ui_font_Font12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_powerunitLabel = lv_label_create(ui_powerPanel);
    lv_obj_set_width(ui_powerunitLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_powerunitLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_powerunitLabel, 19);
    lv_obj_set_y(ui_powerunitLabel, 21);
    lv_obj_set_align(ui_powerunitLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_powerunitLabel, "W");
    lv_obj_set_style_text_color(ui_powerunitLabel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_powerunitLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_powerunitLabel, &ui_font_AGFont14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PowerheadingLabel = lv_label_create(ui_powerPanel);
    lv_obj_set_width(ui_PowerheadingLabel, 45);
    lv_obj_set_height(ui_PowerheadingLabel, 8);
    lv_obj_set_x(ui_PowerheadingLabel, 2);
    lv_obj_set_y(ui_PowerheadingLabel, -23);
    lv_obj_set_align(ui_PowerheadingLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PowerheadingLabel, "POWER");
    lv_obj_set_style_text_color(ui_PowerheadingLabel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PowerheadingLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PowerheadingLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AmpHourPanel = lv_obj_create(ui_AttributePanel);
    lv_obj_set_width(ui_AmpHourPanel, 70);
    lv_obj_set_height(ui_AmpHourPanel, 65);
    lv_obj_set_x(ui_AmpHourPanel, -113);
    lv_obj_set_y(ui_AmpHourPanel, 36);
    lv_obj_set_align(ui_AmpHourPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AmpHourPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_AmpHourPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AmpHourPanel, lv_color_hex(0x3C3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AmpHourPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AmpHourPanel, lv_color_hex(0x313131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AmpHourPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_AmpHourPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_AmpHourPanel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_AmpHourPanel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AmpHourPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_AmpHourPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_AmpHourPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_AmpHourPanel, -2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_AmpHourPanel, -1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AmpHourLabel = lv_label_create(ui_AmpHourPanel);
    lv_obj_set_width(ui_AmpHourLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AmpHourLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AmpHourLabel, 0);
    lv_obj_set_y(ui_AmpHourLabel, 5);
    lv_obj_set_align(ui_AmpHourLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AmpHourLabel, "00");
    lv_obj_set_style_text_color(ui_AmpHourLabel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AmpHourLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AmpHourLabel, &ui_font_Font12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_powerunitLabel2 = lv_label_create(ui_AmpHourPanel);
    lv_obj_set_width(ui_powerunitLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_powerunitLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_powerunitLabel2, 13);
    lv_obj_set_y(ui_powerunitLabel2, 21);
    lv_obj_set_align(ui_powerunitLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_powerunitLabel2, "AH");
    lv_obj_set_style_text_color(ui_powerunitLabel2, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_powerunitLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_powerunitLabel2, &ui_font_AGFont14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AmpHourheadingLabel = lv_label_create(ui_AmpHourPanel);
    lv_obj_set_width(ui_AmpHourheadingLabel, 55);
    lv_obj_set_height(ui_AmpHourheadingLabel, 21);
    lv_obj_set_x(ui_AmpHourheadingLabel, -1);
    lv_obj_set_y(ui_AmpHourheadingLabel, -20);
    lv_obj_set_align(ui_AmpHourheadingLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AmpHourheadingLabel, "AMP - HOUR");
    lv_obj_set_style_text_color(ui_AmpHourheadingLabel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AmpHourheadingLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AmpHourheadingLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SocPanel = lv_obj_create(ui_AttributePanel);
    lv_obj_set_width(ui_SocPanel, 70);
    lv_obj_set_height(ui_SocPanel, 65);
    lv_obj_set_x(ui_SocPanel, 114);
    lv_obj_set_y(ui_SocPanel, -34);
    lv_obj_set_align(ui_SocPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SocPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SocPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SocPanel, lv_color_hex(0x3C3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SocPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SocPanel, lv_color_hex(0x313131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SocPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SocPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_SocPanel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SocPanel, lv_color_hex(0xFFFF10), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SocPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SocPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SocPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_SocPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_SocPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SocLabel = lv_label_create(ui_SocPanel);
    lv_obj_set_width(ui_SocLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SocLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SocLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SocLabel, "00");
    lv_obj_set_style_text_color(ui_SocLabel, lv_color_hex(0xFFFF11), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SocLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SocLabel, &ui_font_Font12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_socunitLabel3 = lv_label_create(ui_SocPanel);
    lv_obj_set_width(ui_socunitLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_socunitLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_socunitLabel3, 17);
    lv_obj_set_y(ui_socunitLabel3, 21);
    lv_obj_set_align(ui_socunitLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_socunitLabel3, "%");
    lv_obj_set_style_text_color(ui_socunitLabel3, lv_color_hex(0xFFFF10), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_socunitLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_socunitLabel3, &ui_font_AGFont14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_socheadingLabel3 = lv_label_create(ui_SocPanel);
    lv_obj_set_width(ui_socheadingLabel3, 27);
    lv_obj_set_height(ui_socheadingLabel3, 15);
    lv_obj_set_x(ui_socheadingLabel3, 5);
    lv_obj_set_y(ui_socheadingLabel3, -20);
    lv_obj_set_align(ui_socheadingLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_socheadingLabel3, "SOC");
    lv_obj_set_style_text_color(ui_socheadingLabel3, lv_color_hex(0xFFFF11), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_socheadingLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_socheadingLabel3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WattHourPanel = lv_obj_create(ui_AttributePanel);
    lv_obj_set_width(ui_WattHourPanel, 70);
    lv_obj_set_height(ui_WattHourPanel, 65);
    lv_obj_set_x(ui_WattHourPanel, -39);
    lv_obj_set_y(ui_WattHourPanel, 34);
    lv_obj_set_align(ui_WattHourPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WattHourPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WattHourPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WattHourPanel, lv_color_hex(0x3C3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WattHourPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WattHourPanel, lv_color_hex(0x313131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WattHourPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WattHourPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_WattHourPanel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_WattHourPanel, lv_color_hex(0xFFFF10), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_WattHourPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_WattHourPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_WattHourPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_WattHourPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_WattHourPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WattHourLabel = lv_label_create(ui_WattHourPanel);
    lv_obj_set_width(ui_WattHourLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WattHourLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WattHourLabel, 5);
    lv_obj_set_y(ui_WattHourLabel, 5);
    lv_obj_set_align(ui_WattHourLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WattHourLabel, "00");
    lv_obj_set_style_text_color(ui_WattHourLabel, lv_color_hex(0xFFFF10), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WattHourLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WattHourLabel, &ui_font_Font12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_watthourunitLabel = lv_label_create(ui_WattHourPanel);
    lv_obj_set_width(ui_watthourunitLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_watthourunitLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_watthourunitLabel, 11);
    lv_obj_set_y(ui_watthourunitLabel, 21);
    lv_obj_set_align(ui_watthourunitLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_watthourunitLabel, "WH");
    lv_obj_set_style_text_color(ui_watthourunitLabel, lv_color_hex(0xFFFF10), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_watthourunitLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_watthourunitLabel, &ui_font_AGFont14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WattHourheadingLabel = lv_label_create(ui_WattHourPanel);
    lv_obj_set_width(ui_WattHourheadingLabel, 44);
    lv_obj_set_height(ui_WattHourheadingLabel, 21);
    lv_obj_set_x(ui_WattHourheadingLabel, -3);
    lv_obj_set_y(ui_WattHourheadingLabel, -18);
    lv_obj_set_align(ui_WattHourheadingLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WattHourheadingLabel, "WATT - HOUR");
    lv_obj_set_style_text_color(ui_WattHourheadingLabel, lv_color_hex(0xFFFF10), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WattHourheadingLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WattHourheadingLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EcoModePanel = lv_obj_create(ui_AttributePanel);
    lv_obj_set_width(ui_EcoModePanel, 70);
    lv_obj_set_height(ui_EcoModePanel, 65);
    lv_obj_set_x(ui_EcoModePanel, 38);
    lv_obj_set_y(ui_EcoModePanel, 34);
    lv_obj_set_align(ui_EcoModePanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_EcoModePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_EcoModePanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_EcoModePanel, lv_color_hex(0x3C3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EcoModePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_EcoModePanel, lv_color_hex(0x313131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_EcoModePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_EcoModePanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_EcoModePanel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_EcoModePanel, lv_color_hex(0xFFFF10), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_EcoModePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_EcoModePanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_EcoModePanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_EcoModePanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_EcoModePanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EcoModeLabel = lv_label_create(ui_EcoModePanel);
    lv_obj_set_width(ui_EcoModeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EcoModeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_EcoModeLabel, 0);
    lv_obj_set_y(ui_EcoModeLabel, 4);
    lv_obj_set_align(ui_EcoModeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EcoModeLabel, "00");
    lv_obj_set_style_text_color(ui_EcoModeLabel, lv_color_hex(0xFFFF10), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_EcoModeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_EcoModeLabel, &ui_font_Font12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EcoModeunitLabel = lv_label_create(ui_EcoModePanel);
    lv_obj_set_width(ui_EcoModeunitLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EcoModeunitLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_EcoModeunitLabel, 11);
    lv_obj_set_y(ui_EcoModeunitLabel, 21);
    lv_obj_set_align(ui_EcoModeunitLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EcoModeunitLabel, "KM");
    lv_obj_set_style_text_color(ui_EcoModeunitLabel, lv_color_hex(0xFFFF10), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_EcoModeunitLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_EcoModeunitLabel, &ui_font_AGFont14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EcoModeheadingLabel = lv_label_create(ui_EcoModePanel);
    lv_obj_set_width(ui_EcoModeheadingLabel, 41);
    lv_obj_set_height(ui_EcoModeheadingLabel, 22);
    lv_obj_set_x(ui_EcoModeheadingLabel, -4);
    lv_obj_set_y(ui_EcoModeheadingLabel, -17);
    lv_obj_set_align(ui_EcoModeheadingLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EcoModeheadingLabel, "Eco - Mode");
    lv_obj_set_style_text_color(ui_EcoModeheadingLabel, lv_color_hex(0xFFFF10), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_EcoModeheadingLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_EcoModeheadingLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SportsModePanel = lv_obj_create(ui_AttributePanel);
    lv_obj_set_width(ui_SportsModePanel, 70);
    lv_obj_set_height(ui_SportsModePanel, 65);
    lv_obj_set_x(ui_SportsModePanel, 114);
    lv_obj_set_y(ui_SportsModePanel, 34);
    lv_obj_set_align(ui_SportsModePanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SportsModePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SportsModePanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SportsModePanel, lv_color_hex(0x3C3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SportsModePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SportsModePanel, lv_color_hex(0x313131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SportsModePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SportsModePanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_SportsModePanel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SportsModePanel, lv_color_hex(0xFFFF10), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SportsModePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SportsModePanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SportsModePanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_SportsModePanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_SportsModePanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SportsModeLabel = lv_label_create(ui_SportsModePanel);
    lv_obj_set_width(ui_SportsModeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SportsModeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SportsModeLabel, 1);
    lv_obj_set_y(ui_SportsModeLabel, 5);
    lv_obj_set_align(ui_SportsModeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SportsModeLabel, "00");
    lv_obj_set_style_text_color(ui_SportsModeLabel, lv_color_hex(0xFFFF10), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SportsModeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SportsModeLabel, &ui_font_Font12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SportsModeunitLabel = lv_label_create(ui_SportsModePanel);
    lv_obj_set_width(ui_SportsModeunitLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SportsModeunitLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SportsModeunitLabel, 11);
    lv_obj_set_y(ui_SportsModeunitLabel, 21);
    lv_obj_set_align(ui_SportsModeunitLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SportsModeunitLabel, "KM");
    lv_obj_set_style_text_color(ui_SportsModeunitLabel, lv_color_hex(0xFFFF10), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SportsModeunitLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SportsModeunitLabel, &ui_font_AGFont14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SportsModeheadingLabel = lv_label_create(ui_SportsModePanel);
    lv_obj_set_width(ui_SportsModeheadingLabel, 48);
    lv_obj_set_height(ui_SportsModeheadingLabel, 23);
    lv_obj_set_x(ui_SportsModeheadingLabel, -1);
    lv_obj_set_y(ui_SportsModeheadingLabel, -17);
    lv_obj_set_align(ui_SportsModeheadingLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SportsModeheadingLabel, "Sports - Mode");
    lv_obj_set_style_text_color(ui_SportsModeheadingLabel, lv_color_hex(0xFFFF10), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SportsModeheadingLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SportsModeheadingLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

}
